frontend/main/routes/main.py
import requests
import json
from flask import Blueprint, render_template, make_response, request, redirect, url_for, current_app
from . import functions as f
# Create a Blueprint object
app = Blueprint('main', __name__, url_prefix='/')




#-----------------------  HOME  -------------------------#

@app.route('/')
def index():
    data = { "page": 1,"per_page" : 10 }

    headers = f.get_headers(without_token=False)

    response = requests.get(f'{current_app.config["API_URL"]}/poemas', json=data, headers=headers)
    print(response.status_code)
    print(response.text)

    #obtener poemas en json
    poemas = json.loads(response.text)
    print (poemas)

    return render_template('home.html', poemas=poemas["poemas"])
    

#-----------------------  HOME  -------------------------#




#-----------------------  LOGIN  -------------------------#

@app.route('/login', methods=['GET','POST'])
def login():
    if request.method == 'POST':
        email= request.form['email']
        password= request.form['password']
        print(email)
        print(password)
        

        data ={"email": email,"password": password}

        headers = f.get_headers(without_token=False)

        response = requests.post(f'{current_app.config["API_URL"]}/auth/login', json = data, headers = headers)
        if response.status_code == 200:

            print (response.status_code)
            print(response.text)

            response = json.loads(response.text)
            token = response["access_token"]
            usuario_id = str(response["id"])
            print (token)

            resp = make_response(redirect(url_for("main.index")))
            resp.set_cookie("access_token",token)
            resp.set_cookie("id", usuario_id)

            return resp
        else:
            return render_template("login.html")
    return render_template("login.html")
    
#-----------------------  LOGIN  -------------------------#




#-----------------------  REGISTER  -------------------------#

@app.route('/register', methods=['GET','POST'])
def register():
    if request.cookies.get('access_token'):
        if request.method == 'POST':
            email= request.form['email']
            password= request.form['password']
            nombre= request.form['nombre']
            rol= request.form['rol']
            print(email)
            print(password)

            

            data ={"email": email,"password": password, "nombre":nombre, "rol":rol}
            print(data)

            headers = f.get_headers(without_token=False)

            requests.post(f'{current_app.config["API_URL"]}/usuarios', json = data, headers = headers)
            


            return redirect(url_for('main.index'))

        else:
            return render_template('register.html', jwt=f.get_jwt())
                
    else:
        return redirect(url_for('main.login'))
#-----------------------  REGISTER  -------------------------#



#-----------------------  LOGOUT  -------------------------#

@app.route('/logout')
def logout():
    resp = make_response(redirect(url_for("main.index")))
    resp.delete_cookie("access_token")
    resp.delete_cookie("id")
    return resp

#-----------------------  LOGOUT  -------------------------#



#-----------------------  CARGAR POEMA  -------------------------#

@app.route('/upload', methods=['GET','POST'])
def add_poem():
    if request.cookies.get('access_token'):
        if request.method == 'POST':
            titulo = request.form['titulo']
            body = request.form['body']
            print(titulo)
            print(body)
            id = f.get_id()
            print(id)
            data = {"titulo": titulo, "usuario_id": id,  "body": body}
            print(data)
            
            headers = f.get_headers(without_token=False)

            if titulo != "" and body != "":
                response = requests.post(f'{current_app.config["API_URL"]}/poemas', json=data, headers=headers)
                print(response)
        
                if response.ok:
                    response = f.json_load(response)
                    return redirect(url_for('main.poema_view', id=response["id"]))
                else:
                    return redirect(url_for('main.add_poem'))
            else:
                return redirect(url_for('main.add_poem'))
        else:
            #Mostrar template
            return render_template('upload.html', jwt=f.get_jwt())
    else:
        return redirect(url_for('main.login'))

#-----------------------  CARGAR POEMA  -------------------------#


#-----------------------  EDITAR  -------------------------#

@app.route('/edit_poema/<id>', methods=['GET','POST'])
def edit_poema(id):
    if request.cookies.get('access_token'):
        if request.method == 'GET':
            poema = f.get_poema(id)
            print(poema.text)
            poema = json.loads(poema.text)
            return render_template('edit_poema.html', poema=poema)

        if request.method == 'POST':
            titulo = request.form['titulo']
            body = request.form['body']
            print(titulo)
            print(body)
            data = {"titulo": titulo,  "body": body}
            print(data)
            f.edit_poema(id, data)
            return redirect(url_for('main.poema_view', id=id))
        else:
            return redirect(url_for('main.edit_poema'))
    else:
        return redirect(url_for('main.login'))
    

@app.route('/edit_calificacion/<id>', methods=['GET','POST'])
def edit_calificacion(id):
    if request.cookies.get('access_token'):
        if request.method == 'GET':
            calificacion = f.get_calificacion(id)
            print(calificacion.text)
            calificacion = json.loads(calificacion.text)
            return render_template('edit_calificacion.html', calificacion=calificacion)

        if request.method == 'POST':
            puntaje = request.form['puntaje']
            comentario = request.form['comentario']

            print(puntaje)
            print(comentario)

            data = {"puntaje": puntaje,  "comentario": comentario}
            print(data)
            f.edit_calificacion(id, data)

            return redirect(url_for('main.index'))
        else:
            return redirect(url_for('main.edit_calificacion'))
    else:
        return redirect(url_for('main.login'))

#-----------------------  EDITAR  -------------------------#


#-----------------------  USUARIO  -------------------------#

@app.route('/usuario')
def usuario():
    if request.cookies.get('access_token'):
        usuario = f.get_user(request.cookies.get('id'))
        usuario = json.loads(usuario.text)
        print(usuario)
        poemas = f.get_poemas_by_id(request.cookies.get('id'))
        print(poemas.text)
        poemas = json.loads(poemas.text)
        for i in poemas['poemas']:
            i['usuario_id']['id'] = str(i['usuario_id']['id'])
  

        return render_template('perfil.html', usuario=usuario, poemas=poemas["poemas"])
    else:
        return redirect(url_for('main.login'))


@app.route('/usuario/<int:id>')
def profile(id):
    if request.cookies.get('access_token'):
        usuario = f.get_user(id)
        print(usuario.text)
        usuario = json.loads(usuario.text)
        print(usuario)
        poemas = f.get_poemas_by_id(id)
        print(poemas.text)
        poemas = json.loads(poemas.text)
        for i in poemas['poemas']:
            i['usuario_id']['id'] = str(i['usuario_id']['id'])


        return render_template('perfil.html', usuario=usuario, poemas=poemas["poemas"])
        
    else:
        return redirect(url_for('main.login'))

#-----------------------  USUARIO  -------------------------#



#-----------------------  DELETE  -------------------------#
@app.route('/delete/poema/<id>')
def delete_poema(id):
    if request.cookies.get('access_token'):
        
        f.delete_poema(id=id)
        return redirect(url_for('main.usuario'))
    else:
        return redirect(url_for('main.login'))

@app.route('/delete/calificacion/<id>')
def delete_calificacion(id):
    if request.cookies.get('access_token'):
        print(id)
        f.delete_comentario(id=id)
        return redirect(url_for('main.index'))
    else:
        return redirect(url_for('main.login'))

@app.route('/delete/usuario/<id>')
def delete_usuario(id):
    if request.cookies.get('access_token'):
        print(id)
        f.delete_user(id=id)
        return redirect(url_for('main.index'))
    else:
        return redirect(url_for('main.login'))

#-----------------------  DELETE  -------------------------#


#-----------------------  CALIFICACION  -------------------------#

@app.route('/calificaciones/<int:id>', methods=['GET','POST'])
def cargar_calificaciones(id):
    if request.cookies.get('access_token'):
        if request.method == 'POST':
            puntaje = request.form['puntaje']
            comentario = request.form['comentario']
            print(puntaje)
            print(comentario)
            usuario_id = f.get_id()
            print(id)
            data = {"puntaje": puntaje, "usuario_id": usuario_id,  "comentario": comentario, "poema_id": id}
            print(data)
            
            headers = f.get_headers(without_token=False)
            if comentario != "" and puntaje != "":
                response = requests.post(f'{current_app.config["API_URL"]}/calificaciones', json=data, headers=headers)
                print(response)
        
                response = f.json_load(response)
                return redirect(url_for('main.poema_view', id=id))
            else:
                return redirect(url_for('main.poema_view'))

#-----------------------  CALIFICACION  -------------------------#



#-----------------------  POEMA  -------------------------#

@app.route('/poema')
def add_poema():
    return render_template('poema.html')


@app.route('/poema/<int:id>')
def poema_view(id):
    if request.cookies.get('access_token'):

frontend/main/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    {% block head %}
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{{url_for('static',filename='base.css')}}" type="text/css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Koulen&amp;display=swap">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"/>
    {% endblock %}


</head>

<body>

    {% block scripts %}
    <!-- Font Awesome -->
    <script src="https://kit.fontawesome.com/ec398cbdc7.js"></script>
    <!-- JS, Popper.js, and jQuery -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"></script>
    {% endblock %}

    {% block nav %}
    <nav class="navbar navbar-expand-lg navbar-dark">
        <div class="container-fluid">
            <!-- LOGO -->
            
            <a href="/" class="navbar-brand">
                <img src="{{url_for('static',filename='images/pluma-logo-blanco.png')}}"  class="navbar-logo" alt="logo-menu-navegacion">
                
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            {% if request.cookies.get('access_token') %}
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <!-- subir poema -->
                    <li >
                        <a class="navbtn" type="button" href="/upload" ><i class="fas fa-pen-nib"></i></a>
                    </li>
                    <!-- usuario -->
                    <li>
                        <a class="navbtn" type="button" href="/usuario"><i class="fas fa-user"></i></a>
                    </li>
                    <li>
                        <div class="search-box">
                        <button class="btn-search"><i class="fas fa-search"></i></button>
                        <input type="text" class="input-search" placeholder="buscar">
                    </div>
                </li>
                </ul>
                <li>
                    <a class="btn"  href="{{url_for('main.logout')}}">Sign out</a>
                </li>
                

                <!-- Login & Registro -->
                <div class="d-flex">
                    <a type="button" href="/register" class="btn">
                        Registrarse
                    </a>
                    {% else %}
                    <a type="button" href="/login" class="btn">
                        Iniciar sesión
                    </a>
                </div>
                {% endif %}
            </div>
        </div>
    </nav>
    {% endblock %}

    {% block content %}
    {% endblock %}

</body>

</html>

frontend/main/templates/edit_calificacion.html
{% extends "base.html" %}

{% block head %}
{{ super() }}
<link rel="stylesheet" href="../static/poema.css" type="text/css">
{% endblock %}

{% block content %}


<body>
    <main class="d-flex flex-colum main-bg shadow">
        <div class="banner">

            <div class="card my-4 mx-4">
                <section>

                    <form method="post" id="form4" action="/edit_calificacion/{{calificacion.id}}">

                        <div class="rating-system3">
                            <h3>Give your Respect</h3>
                            <input type="radio" name='puntaje' id="star5" value="5" />
                            <label for="star5"></label>

                            <input type="radio" name='puntaje' id="star4" value="4" />
                            <label for="star4"></label>

                            <input type="radio" name='puntaje' id="star3" value="3" />
                            <label for="star3"></label>

                            <input type="radio" name='puntaje' id="star2" value="2" />
                            <label for="star2"></label>

                            <input type="radio" name='puntaje' id="star1" value="1" />
                            <label for="star1"></label>

                            <div class="text"></div>
                        </div>


                        <div class="row">
                            <div class="col-xs-12">
                                <div class="form-group">
                                    <textarea class="form-input" name="comentario" placeholder="Your text">{{calificacion.comentario}}</textarea>
                                </div>
                            </div>
                            <div id="btn-post">
                                <button class="btn btn-sm" type="submit"><a>ACEPTAR</a></button>
                            </div>
                    </form>

                </section>
            </div>

        </div>
    </main>
</body>
{% endblock %}

frontend/main/templates/edit_poema.html
{% extends "base.html" %}

{% block head %}
{{ super() }}
<link rel="stylesheet" href="{{url_for('static',filename='upload.css')}}" type="text/css">
{% endblock %}

{% block content %}

<body>
    <main class="d-flex flex-colum main-bg shadow">
        <div class="banner">
            <article class="col-md-8">
            <section>
                <form method="POST" id="form2" action="/edit_poema/{{poema.id}}">
                    <div class="card">
                        <div class="poem-title">
                            <div class="poemtitle">
                                <textarea class="form-control" type="poemtitle" name="titulo" placeholder="body">{{poema.titulo}}</textarea>
                            </div>
                            <div class="poembody">
                                <textarea class="form-control" name="body" rows="3" placeholder="body">{{poema.body}}</textarea>
                            </div>
                        </div>
                    </div>
                    <div id="btn-post">
                        <button class="btn btn-primary btn-primary-outline-success" type="submit">ACEPTAR</button>
                    </div>
                </form>
                  
            </section>
        </article>
</body>
{% endblock %}

frontend/main/templates/home.html
{% extends "base.html" %}

{% block head %}
{{ super() }}
<link rel="stylesheet" href="{{url_for('static',filename='home.css')}}" type="text/css">
{% endblock %}

{% block content %}

        <main class="d-flex flex-colum main-bg shadow">
            <div class="banner">
                <article class="col-md-8">
                    {% for poema in poemas %}
                    <section>
                        <div class="card my-4 mx-4">
                            <div class="row">
                                
                                <div class="col-md-8">
                                    <div class="card-body">
                                        
                                        <h5 class="card-title">{{poema.titulo}}</h5>
                                        <p class="card-text">{{poema.body}}</p>
                                        <a class="card-text" href="{{url_for('main.profile',id=poema.usuario_id.id)}}"><small class="text-muted">{{poema.usuario_id.nombre}}</small></p>
                                        <a href="{{url_for('main.poema_view', id=poema.id)}}" class="btn btn-outline-dark btn-sm">Seguir leyendo</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </section>
                    {%endfor%}
                    <nav aria-label="Page navigation example" class="d-flex justify-content-center">
                        <ul class="pagination">
                            <li class="page-item">
                                <a class="page-link" href="#" aria-label="Previous">
                                    <span aria-hidden="true">«</span>
                                </a>
                            </li>
                            <li class="page-item"><a class="page-link" href="#">1</a></li>
                            <li class="page-item"><a class="page-link" href="#">2</a></li>
                            <li class="page-item"><a class="page-link" href="#">3</a></li>
                            <li class="page-item"><a class="page-link" href="#">... 33</a></li>
                            <li class="page-item">
                                <a class="page-link" href="#" aria-label="Next">
                                    <span aria-hidden="true">»</span>
                                </a>
                            </li>
                        </ul>
                    </nav>
                </article>
           
{% endblock %}

frontend/main/templates/login.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Koulen&amp;display=swap">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"/>
    <link rel="stylesheet" href="{{ url_for('static',filename='login.css')}}" type="text/css">



</head>

<body>

    <!-- Font Awesome -->
    <script src="https://kit.fontawesome.com/ec398cbdc7.js"></script>
    <!-- JS, Popper.js, and jQuery -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"></script>


</body>

</html>


<body class="wallpaper">
    <main class="login animate__animated animate__backInLeft">
        <section>
            <div class="wrapper">
                <img src="{{url_for('static',filename='images/pluma-logo.png')}}" class="login__logo">
                <h1 class="logo__title">Author</h1>
                <div class="card">

                    <div class="card-body">
                        <form class="text-center" method="post" action="/login">

                            <h1 class="login__title">Inicio</h1>

                            <label class="login__label">
                                <input class="form-control" type="email" name="email" placeholder="Email" />
                            </label>

                            <label class="login__label">
                                <input class="form-control" type="password" name="password" placeholder="Password" />
                            </label>

                            <label>
                                <button class="btn btn-primary d-block w-100" type="submit"
                                    style="color:var(--bs-gray-700);background:rgb(234,200,202);border-style:none;">Login</button>
                            </label>
                        </form>
                    </div>
                </div>
            </div>


        </section>


    </main>

</div>

frontend/main/templates/perfil.html
{% extends "base.html" %}

{% block head %}

{{ super() }}
<link rel="stylesheet" href="../static/perfil.css" type="text/css">
{% endblock %}

{% block content %}

<body>
    <div class="header__wrapper">
      <header></header>
      <div class="cols__container">
        <div class="left__col">
          <div class="img__container">
            <img src="../static/images/descarga.jpg" />
            <span></span>
          </div>
          <h2>{{usuario.nombre}}</h2>
          <p>{{usuario.rol}}</p>
          <p>{{usuario.email}}</p>

          <div class="content">
            <p>
              descripcion del perfil 
              o
              historia del usuario 
            </p>

            <ul>
              <li><i class="fab fa-twitter"></i></li>
              <i class="fab fa-pinterest"></i>
              <i class="fab fa-facebook"></i>
              <i class="fab fa-dribbble"></i>
            </ul>
            <a class="btn btn-outline-dark btn-sm" href="{{url_for('main.delete_usuario', id=usuario.id)}}" >Delete Usuario</a>
          </div>
        </div>
        <section>
          {% for poema in poemas %}
          <div class="card my-4 mx-4">
              <div class="row">
                  
                  <div class="col-md-8">
                      <div class="card-body">
                          
                          <h5 class="card-title">{{poema.titulo}}</h5>
                          <p class="card-text">{{poema.body}}</p>
                          <p class="card-text"><small class="text-muted">{{poema.usuario_id.nombre}}</small></p>
                          <div id="btn-delete">
                            {% if poema.usuario_id.id == request.cookies.get('id') %}
                          <a class="btn btn-outline-dark btn-sm" href="{{url_for('main.delete_poema', id=poema.id)}}" >BORRAR</a>
                          <a class="btn btn-outline-dark btn-sm" href="{{url_for('main.edit_poema', id=poema.id)}}" >EDITAR</a>
                          {% endif %}
                        </div>
                      </div>
                  </div>
              </div>
          </div>
          {%endfor%}
      </section>
      
      </div>
    </div>
  </body>
{% endblock %}

frontend/main/templates/poema.html
{% extends "base.html" %}

{% block head %}
{{ super() }}
<link rel="stylesheet" href="../static/poema.css" type="text/css">
{% endblock %}

{% block content %}


<body>
    <main class="d-flex flex-colum main-bg shadow">
        <div class="banner">
            <article class="col-md-6">
                <section>
                    <div class="card my-4 mx-4">
                        <div class="row">

                            <div class="col-md-8">
                                <div class="card-body">

                                    <h5 class="card-title">{{poema.titulo}}</h5>
                                    <p class="card-text">{{poema.body}}</p>
                                    <p class="card-text"><small class="text-muted">{{poema.usuario_id.nombre}}</small>
                                    </p>

                                </div>
                            </div>
                        </div>
                    </div>
                </section>
            
                <div class="card my-4 mx-4">
                <section>
                    
                    <form method="post" id="form4" action="/calificaciones/{{poema.id}}">
                    
                    <div class="rating-system3">
                        <h3>Give your Respect</h3>
                        <input type="radio" name='puntaje' id="star5" value="5"/>
                        <label for="star5"></label>

                        <input type="radio" name='puntaje' id="star4" value="4"/>
                        <label for="star4"></label>

                        <input type="radio" name='puntaje' id="star3" value="3"/>
                        <label for="star3"></label>

                        <input type="radio" name='puntaje' id="star2" value="2"/>
                        <label for="star2"></label>

                        <input type="radio" name='puntaje' id="star1" value="1"/>
                        <label for="star1"></label>

                        <div class="text"></div>
                    </div>

                    
                        <div class="row">
                            <div class="col-xs-12">
                                <div class="form-group">
                                    <textarea class="form-input" name="comentario" placeholder="Your text"></textarea>
                                </div>
                            </div>
                            <div id="btn-post">
                            <button class="btn btn-sm" type="submit"><a>ACEPTAR</a></button>
                        </div>
                    </form>
                    
                </section>
            </div>
            {% for calificacion in calificacion %}
            <div class="card my-4 mx-4">
               <section>
                        <div class="container">
                            <div class="be-comment-block">
                                
                                <div class="be-comment">
                                    <form method="post" action="">

                                    <div class="be-comment-content">
                                        {% if request.cookies.get('access_token') %}
                                        
                    
                                        
                                        <p>{{calificacion.usuario_id.nombre}}</p>
                                        <p class="be-comment-text">{{calificacion.comentario}}</p>
                                        <p>{{calificacion.puntaje}}</p>
                                        {% if calificacion.usuario_id.id == request.cookies.get('id') %}
                                        <a class="btn btn-sm" href="{{url_for('main.delete_calificacion', id=calificacion.id)}}" >BORRAR</a>

                                        <a class="btn btn-sm" href="{{url_for('main.edit_calificacion', id=calificacion.id)}}" >EDITAR</a>
                                        {% endif %}
                                        
                                        {% else %}
                                        <p class="be-comment-text">{{calificacion.calificaciones.comentario}}</p>
                                        <p>{{calificacion.calificaciones.puntaje}}</p>
                                        {% endif %}
                                    </div>
                                    </form> 
                                </div>
                                
                            </div>
                        </div>

                </section>
            </div>
            {% endfor %}
            </article>
        </div>
    </main>
</body>

{% endblock %}

frontend/main/templates/register.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Koulen&amp;display=swap">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"/>
    <link rel="stylesheet" href="{{ url_for('static',filename='login.css')}}" type="text/css">



</head>

<body>

    <!-- Font Awesome -->
    <script src="https://kit.fontawesome.com/ec398cbdc7.js"></script>
    <!-- JS, Popper.js, and jQuery -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"></script>


</body>

</html>


<body class="wallpaper">
    <main class="login animate__animated animate__backInLeft">
        <section>
            <div class="wrapper">
                <img src="{{url_for('static',filename='images/pluma-logo.png')}}" class="login__logo">
                <h1 class="logo__title">Author</h1>
                <div class="card">

                    <div class="card-body">
                        <form class="text-center" method="post" action="/register">

                            <h1 class="login__title">Registro</h1>

                            <label class="login__label">
                                <input class="form-control" type="email" name="email" placeholder="Email" />
                            </label>

                            <label class="login__label">
                                <input class="form-control" type="password" name="password" placeholder="Password" />
                            </label>

                            <label class="login__label">
                                <input class="form-control" type="name" name="nombre" placeholder="Nombre" />
                            </label>
                            <label class="login__label">
                                <input class="form-control"  name="rol" placeholder="Rol" />
                            </label>

                            <label>
                                <button class="btn btn-primary d-block w-100" type="submit"
                                    style="color:var(--bs-gray-700);background:rgb(234,200,202);border-style:none;">Resgister</button>
                            </label>
                        </form>
                    </div>
                </div>
            </div>


        </section>


    </main>

</div>